// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wlpjoojxlvfqjjedhujf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscGpvb2p4bHZmcWpqZWRodWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2MjIxNTksImV4cCI6MjA4MjE5ODE1OX0.Xbo2ISyEYVQBiqBID9eD85bndQV7qktoJ_4X7K7FVyc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
